# Generated by Django 6.1.1 on 2026-09-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='statut',
            field=models.CharField(choices=[('disponible', 'DISPONIBLE'), ('louee', 'Louée'), ('maintenance', 'En maintenance')], default='disponible', max_length=20),
        ),
    ]
